### PR TITLE
[WIP] Remove abis.json from beta templates

### PR DESCRIPTION
**Pull request by sohkai**
Update beta template's `abis.json` for new Vault and Finance.

### CODE REVIEW

**Comment by bingen** [comment]
Wasn't this file supposed to be autogenerated (with `npm run prepublish`) and git-ignored?

**Comment by sohkai** [comment]
Oh was it? I guess I'll add the .gitignore instead?

But we are meant to publish this, yeah?

**Comment by bingen** [comment]
I don't think so, I think that's why `npm run prepublish` was added. Anyway we should either `git rm abis.json` or remove it from `.gitignore`.

**Comment by izqui** [comment]
Close? @sohkai

**Comment by bingen** [comment]
Shouldn't we do `git rm abis.json` before closing?

**Comment by sohkai** [comment]
Yes, I'll do that now!

**Pull request merged**
