### PR TITLE
Add prepublish script before publishing to aragonPM

### PR DESCRIPTION
**Pull request by sohkai**
Requires https://github.com/aragon/aragon-cli/pull/571 (and the aragonCLI upgrade).

cc @0xGabi

### CODE REVIEW

**Comment by 0xGabi** [comment]
LGTM 

We will probably release a major version cause we introduced a breaking change making ipfs optional. 

We could also release a minor only with the PRs for updating `apm publish`.

**Comment by 0xGabi** [comment]
`aragon apm publish` now needs confirmation so I included the `--skip-confirmation` flag to skip confirmation. 

@sohkai What do you think about propagate content. Is this something we want to do as default on each publish? There is other flag: `--propagate-content` that we might want to configure as well.

**Comment by sohkai** [comment]
@0xGabi Having that flag would be useful too, although if it prompts users by default, I think that's fine as well.

**Comment by 0xGabi** [comment]
Oh ok, I thought it might break the CI. But I just realize that all checks have pass 😅

Will revert last commit then.

**Comment by sohkai** [comment]
Ah, we don't publish from the CI 😄

**Comment by 0xGabi** [comment]
@sohkai Ready 👍

**Review by facuspagnuolo — APPROVED** [review]

**Pull request merged**
