### PR TITLE
[WIP] Move Registry app from aragonlabs/registry to future-apps

### PR DESCRIPTION
**Pull request by izqui**
Basically copies @onbjerg's registry app from https://github.com/aragonlabs/registry for easy use from aragon-apps templates to build a TCR template.

Also minor changes so it works with aragonOS 3.

Needs testing, documentation and review.

### CODE REVIEW

**Comment by onbjerg** [comment]
that's a complex smart contract, I approve

**Comment by izqui** [comment]
We should refactor it soon, the technical debt this contract will bring is going to be a huge weight

**Comment by tarrencev** [comment]
I've been thinking through the implementation of an app that uses this registry as a way to deduplicate data between multiple instances of the app (since it is content addressed). I think in order for this to work the registry needs to implement reference counting. Otherwise it's possible to have app1 and app2 both depending on some entry in the registry and app1 naively deleting the entry while app2 still depends on it. Does that make sense or am I missing something?

**Comment by izqui** [comment]
Not super relevant to have in aragon-apps given that the TCR implementation has been tabled for now.

**Pull request closed without merging**
