### PR TITLE
Voting: updates

### PR DESCRIPTION
**Pull request by bpierre**
- [x] Move to parcel (from react-scripts)
- [x] Move to react-spring (from react-motion)
- [x] Card layout (issue: https://github.com/aragon/design/issues/10)
- [x] Display the user vote
- [x] Display the correct balance (PR: https://github.com/aragon/aragon-apps/pull/449)
- [x] Execute a vote (issue: https://github.com/aragon/aragon-apps/issues/216#issuecomment-420243809, PR: https://github.com/aragon/aragon-apps/pull/450)
- [x] Explicitly change a vote (PR: https://github.com/aragon/aragon-apps/pull/450)

### CODE REVIEW

**Comment by izqui** [comment]
After voting NO, the state of the card is not updating:

**Comment by bpierre** [comment]
@izqui it was related to Chrome and the way the props were propagated. It should be fixed now, and the flickering issues too! You need to `npm i` again to have the latest version of `@aragon/ui`.

**Comment by izqui** [comment]
What are your thoughts on https://github.com/aragon/aragon-apps/pull/448#discussion_r218323797? Making the change at the same time to all the apps would definitely make aragen's life easier.

**Comment by bpierre** [comment]
@izqui sorry I missed this comment: done!

**Pull request merged**
