### PR TITLE
Add test task to CI

### PR DESCRIPTION
**Pull request by bingen**

### CODE REVIEW

**Comment by sohkai** [comment]
Do we need to rebase this on top of #180?

**Comment by bingen** [comment]
Yes, good idea.

**Comment by bingen** [comment]
Hm, now we have that weird gas error for Vault (it works with `truffle test` and `npm run coverage`, but not for `npm run test`). Will try to fix it.

**Comment by bingen** [comment]
Vault tests are fixed now. I have another PR almost ready that uses docker geth image for vault tests, but relies on #160 so I'll submit it once that one is merged.

**Pull request merged**
