### PR TITLE
templates: Add tests for Beta Templates

### LINKED ISSUE #74: DAO integration tests against Beta templates
Construct a dummy DAO with the current apps that will be part of the v0.5 release and interact with it asserting all parts are working as expected. There shouldn't be any surprises but a full test case would be great to have!

~Blocked by #72~

### PR DESCRIPTION
**Pull request by bingen**
Closes #74

### CODE REVIEW

**Comment by bingen** [comment]
It should be merged (and conflicts fixed) after #115

**Comment by renexdev** [comment]
Hi @bingen, thanks for the tests
Summary:
we need the following (after docker branch is ready):
1) Copy the scrips folder (taken from docker branch in beta folder)
2) Add ` "prepublish": "truffle compile && node scripts/extract-abis.js",` in `package.json`
3) Upgrade `"@aragon/id": "^1.2.1",` in  in `package.json` (Thanks, was messy to change imports  manually)
4) Add ´    "ethereumjs-abi": "^0.6.4",´ in  `package.json` (needed by `/@aragon/test-helpers/evmScript.js`)

Linting and  21 tests passed!! =)
```
   "lint": "solium --dir ./contracts",
    "test": "TRUFFLE_TEST=true npm run ganache-cli:dev",
    "test:gas": "GAS_REPORTER=true npm test",
```

**Comment by bingen** [comment]
Hi @renexdev 

yes, I have locally merged those branches and I think I have already managed those issues. I'll submit a new PR soon.

About (4), `ethereumjs-abi` is already in `test-helpers` `package.json`, make sure you are doing `npm install` there.

Thanks!

**Comment by bingen** [comment]
Replaced by #128

**Pull request closed without merging**
